### ISSUE TITLE
error when detecting dataview test

### ISSUE THREAD

**Issue by keriati** [Modernizr/grunt-modernizr#104]
Hello!
I have this in my code:  "... Modernizr.dataview === true ...", and in my grunt config: __matchCommunityTests: true,__

When I run the build, I get this error:

```
Looking for Modernizr references

in dist/scripts/main.js
>> dataview
>> json
>> geolocation
>> history

in dist/styles/main.css
>> svg

Downloading source files
cache modernizr-latest.js
cache modernizr.load.1.5.4.js

Downloading community files
cache json.js
404 dataview.js

>> Generating a custom Modernizr build
>> Uglifying

>> Wrote file to dist/scripts/vendor/modernizr.js
>> The following tests could not be downloaded
>>     
>>     404 http://modernizr.com/Modernizr/Modernizr/87c723720a48254ae37ffd56829e32a96f5c5496/feature-detects/dataview.js
>>     
>>     Check the Modulizr API for more info:
>>     https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modulizr.js#L15-157
```

When I add __tests: ['dataview-api'],__ to the config, and remove __matchCommunityTests: true,__ I end up with the expected result:

```

Looking for Modernizr references

in dist/scripts/main.js
>> json
>> geolocation
>> history

in dist/styles/main.css
>> svg

Downloading source files
cache modernizr-latest.js
cache modernizr.load.1.5.4.js

Downloading community files
cache dataview-api.js
cache json.js

>> Generating a custom Modernizr build
>> Uglifying

>> Wrote file to dist/scripts/vendor/modernizr.js
```

So it looks like Modernizr.dataview needs the dataview-api test, but the grunt job fails to recognize this :(

**Comment by patrickkettner** [comment]
a ton of the project has changed to the point where this would no longer be relevant to the project. I am super sorry you never got your answer, but if you are still hitting this issue in grunt-modernizr 1.0+, please open up an issue on the [customizr repo](https://github.com/modernizr/customizr/issues/new), where all of this logic lives now
