### ISSUE TITLE
Build script not detecting classes in Javascript?

### ISSUE THREAD

**Issue by CFXd** [Modernizr/grunt-modernizr#105]
I'm not sure if this is unexpected behavior, but neither of these selectors:

 1. `$('.touch .foo')`
 2. `$('.no-touch .foo')`

cause the `touch` test to be included in my build. Using the `Modernizr.touch` test does work though, so wasn't sure if this is expected behavior or an issue.

I would think that if the builder parses my CSS file for classes that it would also parse JS but it appears not...

Is this intentional?

**Comment by doctyper** [comment]
Yes this is intentional. The JavaScript detection requires a leading a-z character to trigger a match. It's one of the safeguards against false-positives.

**Comment by CFXd** [comment]
Right on, thanks for the quick reply.

**Comment by CFXd** [comment]
For the record, just tried this with `$('html.touch .foo')` and `$('html.no-touch .foo')` and it's not being picked up.
