### ISSUE TITLE
Manually configuring files does not work

### ISSUE THREAD

**Issue by Jpunt** [Modernizr/grunt-modernizr#108]
I want to manually target some files instead of crawling my full project. This however, does not seem to work:

```js
    modernizr: {
      build: {
        devFile: 'remote',
        outputFile: 'build/modernizr-custom.js',
        files: {
          src: ['build/styles.css', 'build/client.js']
        },
        parseFiles: false,
        uglify: true,
        extra: {
          shiv: true,
          printshiv: false,
          load: true,
          mq: false,
          cssclasses: true
        }
      }
    }
```

When I leave out the `files` and set `parseFiles` to `true` it'll work, but I rather target those two files explicitly to prevent some unused tests to be included.

**Comment by patrickkettner** [comment]
this is working for me. If you are still having problems, can you open an issue on [customizr](https://github.com/modernizr/customizr/issues/new)?All of the crawling and parsing logic lives there now.
