### ISSUE TITLE
npm test fail

### ISSUE THREAD

**Issue by 2silver** [Modernizr/grunt-modernizr#110]
I did the following steps.

    git clone https://github.com/Modernizr/grunt-modernizr
    cd grunt-modernizr && npm i --save-dev
    npm test

The test fails with

    >> Generating a custom Modernizr build
    >> Uglifying
    Fatal error: Unexpected character ''
        1) should find all available tests in project
             AssertionError: expected "Fatal error: Unexpected character '\u001f'\u0007" to contain ">> Wrote file to build/modernizr-custom.js"
    
    
      custom builds
        community tests
          2) should find all available tests in project
             Error: done() called multiple times
    
    npm ERR! Test failed.  See above for more details.

**Comment by patrickkettner** [comment]
the tests have been fixed in 0.6.1
