### ISSUE TITLE
default 'devFile' action from static assignment to dynamic assignment using '.bowerrc'

### ISSUE THREAD

**Issue by Jnull** [Modernizr/grunt-modernizr#111]
https://github.com/Modernizr/grunt-modernizr#devfile-string

While in my project i have moved my bower_components by changing the default *.bowerrc* config:   

```
{
  "directory": "bower_components",
  "dependencies": true,
  "devDependencies": true
}
```
To the modified *.bowerrc* config: 
```
{
  "directory": "app/bower_components",
  "dependencies": true,
  "devDependencies": true
}
```
devFile string should automatically find *bower_components* folder using the *.bowerrc* config using the directory property string value (*"directory": "app/bower_components"*).

**Comment by patrickkettner** [comment]
@Jnull I am not sure I understand your request. It doesn't automatically find it in any cases, regardless of whether or not you have modified the bower directory. That is why it is marked as `required`.

Can you elaborate on what you are asking for?

**Comment by Jnull** [comment]
I don't have this setup anymore,  so I'm closing this.
