### ISSUE TITLE
Explicitly requiring css-calc does not work in 0.6

### ISSUE THREAD

**Issue by kr1x** [Modernizr/grunt-modernizr#112]
Since I updated grunt-modernizr in my environment from 0.5.2 to ~0.6, the test for css-calc can not be loaded :-(

That's my current modernizr task in my Gruntfile.js:
```
        modernizr: {
            dist: {
                devFile: 'bower_components/modernizr/modernizr.js',
                outputFile: 'web/js/modernizr.min.js',
                files: {
                    src: [
                        'web/js/{,*/}*.js',
                        'web/css/{,*/}*.css'
                    ]
                },
                extensibility : {
                    "prefixes" : true
                },
                tests : [
                    "css-calc",
                    "touch"
                ],
                uglify: false
            }
        },
```

With 0.5.2 I can clearly see the test for css-calc in the modernizr.js, but with 0.6 the test is not added to the file. 

Can anyone confirm this behaviour?

**Comment by timomayer** [comment]
i think i have the same issue with adding the object-fit test to the custom tests :(

**Comment by cah4a** [comment]
I have the same issue.
On 0.6.0 version `css-calc` test doesn't include in result file.

**Comment by DrCord** [comment]
The value appears to "csscalc" now, any property with a "/" or "-" doesn't work and has to have it removed. Certain properties seem to need the "css" (or other prefix) on front ("csscalc") and certain don't (example: "dom/mutationoberver" needs to be just "muationobserver").

**Comment by patrickkettner** [comment]
when the switch to customizr was made, there was a breaking change in the way that you include tests. It used to be the AMD path, now it is the Modernizr property name. This is the same as the html class of `Modernizr.[foo]` bit that you access normally. 

There can't be a `/` or a `-` in that name
