### ISSUE TITLE
CSS3, HTML5, Misc settings?

### ISSUE THREAD

**Issue by sensaetions** [Modernizr/grunt-modernizr#117]
What settings do I need to use in order to enable the CSS3, HTML5 and Misc settings (that are found on Modernizr's download page (http://modernizr.com/download/))?

**Comment by philwolstenholme** [comment]
These are outlined on the module's page aren't they?: https://github.com/Modernizr/grunt-modernizr#config-options

The default options match the defaults on http://modernizr.com/download

**Comment by patrickkettner** [comment]
thanks, @philwolstenholme!
