### ISSUE TITLE
Ensure all failures result in non-zero exit status.

### ISSUE THREAD

**Issue by patricknelson** [Modernizr/grunt-modernizr#120]
Separating this out in case this is an unrelated issue to the comment I posted here in issue #118. 
https://github.com/Modernizr/grunt-modernizr/issues/118#issuecomment-140217564

It appears that not all errors/failures will fail with a non-zero exit status, which is detrimental to any deploy processes (e.g. capistrano in my case). Ideally, any failure would result in this status in order to signal calling processes that there was an issue.

**Comment by patrickkettner** [comment]
This happens now, since we have a single point of failure (unlike before)

**Comment by patricknelson** [comment]
Going through all my ancient issues here...  thanks @patrickkettner :+1:  Huge help.
