### ISSUE TITLE
Some references to tests are not picked up when building custom build

### ISSUE THREAD

**Issue by SuneRadich** [Modernizr/grunt-modernizr#122]
Im trying to build a custom build of Modernizr based on the stuff I actually use - and as far as I can see, that is exactly what this grunt task is for.

I'm using `csspointerevents`, but I cant seem to get it to pick up that I use that test.

I have tried numerous other modernizr tests, just to see if my setup works, and can see that things like `vibrate`, `canvas`, `svg`, `multiplebgs`, and `webworkers` work as expected. If I use a test in either Javascript or CSS (scss file) the test is included in my built file - just as I would expect.

But other tests like `csspointerevents`, `cssmask`, `lastchild` and `cssresize` are not picked up, and thus not included in the built file.

My grunt config looks like this:

    	production: {
		"parseFiles": true,
		"customTests": [],	
		"devFile": "<%= package.resources %>/js/standalone/modernizr-dev.js",
		"outputFile": "<%= package.resources %>/js/standalone/modernizr.min.js",
		"files" : {
			"src": [
				'<%= package.resources %>/js/*',
				'<%= package.resources %>/js/{modules,plugins}/**/*',
				'<%= package.resources %>/sass/{components,core,elements}/**/*',
			]
		},
		"extensibility": [
			"setClasses"
		],
		//"matchCommunityTests": false,
		"uglify": true
	}

So it seems to me that some of the tests are not able to be picked up by the plugin? I am using modernizr-dev.js version 3.0.0-alpha.4 (Custom Build) downloaded from modernizr.com - and I have confirmed that all the tests I have tried are in fact included in that -dev build.

Have I missed something, a setting or something that would limit the tests available to the grunt task?

**Comment by SuneRadich** [comment]
Update, when matchCommunityTests is enabled, more of my missing tests show up. Now I can get  `lastchild` and `cssresize`

But the one I need, `csspointerevents`, is still missing from the built file.

**Comment by patrickkettner** [comment]
@SuneRadich this is actually a bug in [customizr](https://github.com/Modernizr/customizr) - could you [open up an issue over there](https://github.com/Modernizr/customizr/issues/new)?
