### ISSUE TITLE
Unable to install grunt-modernizr 1.0.0 on Windows

### ISSUE THREAD

**Issue by jenssimon** [Modernizr/grunt-modernizr#125]
When I try to install grunt-modernizr 1.0.0 I get the following error on ````npm install````:

````
> grunt-modernizr@1.0.0 postinstall C:\Users\Jens\dev\dw\BabyOne\repo\node_modules\grunt-modernizr
> if [[ -d node_modules/modernizr ]]; then ( cd node_modules/modernizr; npm install --production; cd -; ); fi

"-d" kann syntaktisch an dieser Stelle nicht verarbeitet werden.
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Jens\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm
-cli.js" "install"
npm ERR! node v4.1.0
npm ERR! npm  v2.7.3
npm ERR! code ELIFECYCLE

npm ERR! grunt-modernizr@1.0.0 postinstall: `if [[ -d node_modules/modernizr ]]; then ( cd node_modules/modernizr; npm i
nstall --production; cd -; ); fi`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the grunt-modernizr@1.0.0 postinstall script 'if [[ -d node_modules/modernizr ]]; then ( cd node_modu
les/modernizr; npm install --production; cd -; ); fi'.
npm ERR! This is most likely a problem with the grunt-modernizr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     if [[ -d node_modules/modernizr ]]; then ( cd node_modules/modernizr; npm install --production; cd -; ); fi

npm ERR! You can get their info via:
npm ERR!     npm owner ls grunt-modernizr
npm ERR! There is likely additional logging output above.
````

**Comment by wandrew** [comment]
I am encountering the same error.  My Node package manager version was 2.10.1 and the current version is 2.14.4.  I updated and tried again to the same result.

**Comment by Sebastian-Fitzner** [comment]
same here ...

**Comment by timothywisdom** [comment]
same here

**Comment by timothywisdom** [comment]
I was able to get this other grunt builder to install:
https://github.com/jon301/grunt-modernizr-builder

**Comment by jochenvanwylick** [comment]
Same here!

**Comment by jorrit** [comment]
package.conf contains bash/linux only code, unfortunately.

**Comment by alexan** [comment]
It is necessary because they want to support some legacy npm version.
IMO this support should be moved to a separate fork.

If this does not get sorted out soon I consider making my own fork without it.
But I would prefer a clean base repository.

**Comment by ste93cry** [comment]
:+1: same issue here

**Comment by coaster3000** [comment]
There are two open pull requests for this issue. I would hope something is done about them soon. I need this to be fixed...

Have been considering downgrading the version, but reluctant...

**Comment by ste93cry** [comment]
> Have been considering downgrading the version, but reluctant... 

Me too, this should indeed be fixed asap

**Comment by coaster3000** [comment]
Hey doc, mind helping us out here? Don't mean to sound rude or anything, but there are two open pull requests. The regressive commit is authored by you. Are you permitted to handle pull requests?

https://github.com/Modernizr/grunt-modernizr/commit/30af51c76c5f6bd28e88eeeee835631b99e79f51 -- Initial Regressive Commit

@doctyper Ping!

**Comment by patrickkettner** [comment]
sorry everyone!
merged in a fix in 1.0.1

**Comment by ste93cry** [comment]
thank you!

**Comment by jorrit** [comment]
Thanks for creating version 1.0.1. I have found some minor issues in the new postinstall file and I have created #131 for this. Could you review this change?

**Comment by jorrit** [comment]
This issue can be closed as fixed!

**Comment by patrickkettner** [comment]
cheers!
