### ISSUE TITLE
Not detecting touch/no-touch

### ISSUE THREAD

**Issue by JayCarney** [Modernizr/grunt-modernizr#132]
running the build using 1.0.0 I'm not getting a positive for the touch test, older versions of the build tool worked fine, adding "touch" to tests doesn't seem to fix the issue

**Comment by JayCarney** [comment]
Just realised that they changed this to "touchevents", my bad

**Comment by patrickkettner** [comment]
Hey @jaycarney!
1.0.0 uses Modernizr 3, which renamed touch to touchEvents

Cheers!
