### ISSUE TITLE
Duplicate check on my css files

### ISSUE THREAD

**Issue by andreasisaak** [Modernizr/grunt-modernizr#134]
grunt-modernizr check my css files several times:

<img width="324" alt="screenshot 2015-11-16 22 02 49" src="https://cloud.githubusercontent.com/assets/156767/11194678/cd325b24-8cad-11e5-8ded-b333ae00bb54.png">

**Comment by patrickkettner** [comment]
@andreasisaak could you post a demo project showing the problem? I am not able to replicate the issue

**Comment by andreasisaak** [comment]
Yes, I will try it!

**Comment by patrickkettner** [comment]
ping @andreasisaak

**Comment by patrickkettner** [comment]
give me a shout if you can post a repro, cheers!
