### ISSUE TITLE
Common options?

### ISSUE THREAD

**Issue by FezVrasta** [Modernizr/grunt-modernizr#136]
Usually grunt plugins allow me to do like this:

````js
modernizr: {
  options: {
    tests:  [ 'hiddenscroll' ],
    crawl:  false
  },
  production: {
    dest:   'app/components/modernizr/modernizr-custom.min.js'
  },
  dev: {
    dest:   'app/components/modernizr/modernizr-custom.js',
    uglify: false
  }
}
````

But doing this with grunt-modernizr, the `options` property is completely ignored.

Am I doing something wrong or is not supported? If not, can it be added?

Thanks.

**Comment by patrickkettner** [comment]
it is not currently supported.

Its a good idea, however

**Comment by FezVrasta** [comment]
Any chance to get this feature anytime soon? I've 0 experience with grunt plugins, otherwise I would have submitted a PR...

**Comment by patrickkettner** [comment]
​Probably not soon, as no one is actively working on it and it is the week
of thanksgiving
