### ISSUE TITLE
Error after grunt-modernizr update

### ISSUE THREAD

**Issue by stephanfriedrich** [Modernizr/grunt-modernizr#142]
Hi,
at first thx for your nice modul.
I updated my grunt modules, now if i run grunt within modernizr i get the following error:

**Building your customized Modernizr Fatal error: undefined is not a function**

I updated grunt-modernizr from ^0.6  →  ^1.0
node -v:  v0.12.10
npm -v : 3.5.3

**here are my old specs for grunt-modernizr 0.6:**
- used modernizr.js version [2.8.3](http://modernizr.com/download/#-fontface-backgroundsize-borderimage-borderradius-boxshadow-flexbox-hsla-multiplebgs-opacity-rgba-textshadow-cssanimations-csscolumns-generatedcontent-cssgradients-cssreflections-csstransforms-cs)
- my grunt-modernizr config:
  
  ```
  modernizr: {
    dist: {
      "devFile" : "assets/js/vendor/modernizr.js",
      "outputFile" : "build/assets/js/modernizr.js",
      "extra" : {
        "cssclasses" : true,
        "load" : false,
        "mq" : false,
        "printshiv" : true,
        "shiv" : true
      },<br>
      "files" : {
        "src": ['components/app/**/*.js', 'build/**/*.css']
      }
    }
  },
  ```

**here are my new specs for grunt-modernizr 1.0.2:**
- now i used the modernizr [dev-source version 3.3.1](https://modernizr.com/download?adownload-ambientlight-animation-apng-appearance-applicationcache-atobbtoa-audio-audioloop-audiopreload-backdropfilter-backgroundblendmode-backgroundcliptext-backgroundsize-batteryapi-bdi-beacon-bgpositionshorthand-bgpositionxy-bgrepeatspace_bgrepeatround-bgsizecover-blobconstructor-bloburls-blobworkers-borderimage-borderradius-boxshadow-boxsizing-canvas-canvasblending-canvastext-canvaswinding-capture-checked-classlist-contains-contenteditable-contextmenu-cookies-cors-createelementattrs_createelement_attrs-cryptography-cssall-cssanimations-csscalc-csschunit-csscolumns-cssescape-cssexunit-cssfilters-cssgradients-csshairline-csshyphens_softhyphens_softhyphensfind-cssinvalid-cssmask-csspointerevents-csspositionsticky-csspseudoanimations-csspseudotransitions-cssreflections-cssremunit-cssresize-cssscrollbar-csstransforms-csstransforms3d-csstransitions-cssvalid-cssvhunit-cssvmaxunit-cssvminunit-cssvwunit-cubicbezierrange-customevent-customprotocolhandler-dart-datachannel-datalistelem-dataset-datauri-dataview-dataworkers-details-devicemotion_deviceorientation-directory-display_runin-displaytable-documentfragment-ellipsis-emoji-es5-es5array-es5date-es5function-es5object-es5string-es5syntax-es5undefined-es6array-es6collections-es6math-es6number-es6object-es6string-eventlistener-eventsource-exiforientation-fetch-fileinput-filereader-filesystem-flash-flexbox-flexboxlegacy-flexboxtweener-flexwrap-fontface-forcetouch-formattribute-formvalidation-framed-fullscreen-gamepads-generatedcontent-generators-geolocation-getrandomvalues-getusermedia-hashchange-hidden-hiddenscroll-history-hsla-htmlimports-ie8compat-imgcrossorigin-indexeddb-indexeddbblob-inlinesvg-input-inputformaction-inputformenctype-inputformmethod-inputformtarget-inputtypes-intl-jpeg2000-jpegxr-json-lastchild-ligatures-localizednumber-localstorage-lowbandwidth-lowbattery-matchmedia-mathml-mediaqueries-microdata-multiplebgs-mutationobserver-notification-nthchild-objectfit-olreversed-oninput-opacity-outputelem-overflowscrolling-pagevisibility-peerconnection-performance-picture-placeholder-pointerevents-pointerlock-postmessage-preserve3d-progressbar_meter-promises-proximity-queryselector-quotamanagement-regions-requestanimationframe-requestautocomplete-rgba-ruby-sandbox-scriptasync-scriptdefer-scrollsnappoints-seamless-search-serviceworker-sessionstorage-shapes-sharedworkers-siblinggeneral-sizes-smil-speechrecognition-speechsynthesis-srcdoc-srcset-strictmode-stylescoped-subpixelfont-supports-svg-svgasimg-svgclippaths-svgfilters-svgforeignobject-target-template-templatestrings-textalignlast-textareamaxlength-textshadow-texttrackapi_track-time-todataurljpeg_todataurlpng_todataurlwebp-touchevents-transferables-typedarrays-unicode-unicoderange-unknownelements-urlparser-userdata-userselect-vibrate-video-videoautoplay-videoloop-videopreload-vml-webaudio-webgl-webglextensions-webintents-webp-webpalpha-webpanimation-webplossless_webp_lossless-websockets-websocketsbinary-websqldatabase-webworkers-willchange-wrapflow-xdomainrequest-xhr2-xhrresponsetype-xhrresponsetypearraybuffer-xhrresponsetypeblob-xhrresponsetypedocument-xhrresponsetypejson-xhrresponsetypetext-addtest-atrule-domprefixes-hasevent-mq-prefixed-prefixedcss-prefixedcssvalue-prefixes-setclasses-shiv-testallprops-testprop-teststyles)
- my updated grunt-modernizr config:
  
  ```
  modernizr: {
    dist: {
      "devFile" : "assets/js/vendor/modernizr.js",
      "dest" : "build/assets/js/modernizr.js",
      "options" : [
        "setClasses",
        "html5printshiv",
        "html5shiv"
      ],
      "files" : {
        "src": ['components/app/**/*.js', 'build/**/*.css']
      }
    }
  },
  ```

Is this new setting correct ?
If i run `grunt --degug modernizr` the task finished successfully.

Can you Help me plz

**Comment by rejas** [comment]
Please try to update your node version to something currently supported (>6) and report back if possible.
