### ISSUE TITLE
package.json pulling development branch of Customizr 

### ISSUE THREAD

**Issue by aragacalledpat** [Modernizr/grunt-modernizr#146]
Hello!  Thank you so much for offering this grunt task - it's super helpful!

Just wondering why you guys are pulling from the Customizr development branch instead of a stable release.  I'm building a piece of software where stability is extremely important, and I'm reluctant to rely on something that might change/break without me manually updating.

Thanks!

**Comment by rubendv** [comment]
This is breaking when installing through yarn because the hash no longer matches the hash in our lockfile.

**Comment by joemcloE** [comment]
This again has broken installing through yarn, due to an upgrade to customizr 1.0.0-alpha, and looks like a reversing back to 1.0.0

**Comment by tomdxw** [comment]
I'm also seeing yarn breaking due to a mismatched hash:

```
error https://github.com/Modernizr/customizr/tarball/develop: Fetch succeeded for undefined. However, extracting "https://github.com/Modernizr/customizr/tarball/develop" resulted in hash "7f45419c18d8fefc1378cd1ca00bd2aa3aa501b5", which did not match the requested hash "bf72bdbc0e693e253cfc2b80180eb7b984753111".
```

**Comment by mikemellor11** [comment]
This problem seems to have popped up again.

npm ERR! 404 Not Found - GET https://codeload.github.com/Modernizr/customizr/legacy.tar.gz/develop

Any chance this file can be put back at the same location

**Comment by rejas** [comment]
I think you have to ask @doctyper to add a develop branch to this fork, since you seem to try to access that...

**Comment by angorora** [comment]
Actually this is because these packages have been moved  update the version of modernizr in pckage.json to 2 versions later

**Comment by schell** [comment]
I'm running into this as well. Is there a fork anywhere that folks are using?
