### ISSUE TITLE
Preventing a network request

### ISSUE THREAD

**Issue by gxxcastillo** [Modernizr/grunt-modernizr#15]
I might be going about this wrong but I'm using grunt modernizr within a deploy script and there have been a few occasions where there is a problem with the network and the deploy fails due to grunt-modernizr not being able to download source files.  Is it possible to have grunt-modernizr always use my local version of of modernizr?  Or maybe a way to force it to always use the cached version?

It would be great if I could avoid checking in the custom built modernizr into my repo.

**Comment by brunobatista** [comment]
+1. In my case I have proxy behind. Output error:

```bash
Downloading community files
>> A server error occurred attempting to download a file:
Fatal error: connect ECONNREFUSED
```

**Comment by radum** [comment]
@brunobatista Make sure you have the HTTP_PROXY env vars setup. This has been fixed a long time ago.

**Comment by brunobatista** [comment]
Thanks @radum, the issue is with bower http://bower.io/docs/config/#proxy, need use with proxy settings.
