### ISSUE TITLE
Unable to add "cssgrid", "cssgridlegacy"

### ISSUE THREAD

**Issue by Hlsgs** [Modernizr/grunt-modernizr#153]
This config doesn't work properly, as only `touchevents` is added:
```
{
  "crawl": false,
  "customTests": [],
  "dest": "/PATH/TO/modernizr-output.js",
  "tests": [
    "touchevents",
    [
      "cssgrid",
      "cssgridlegacy"
    ]
  ],
  "options": [
    "setClasses"
  ],
  "uglify": true
}
```

This doesn't work either:
```
{
  "crawl": false,
  "customTests": [],
  "dest": "/PATH/TO/modernizr-output.js",
  "tests": [
    "touchevents",
    "cssgrid",
    "cssgridlegacy"
  ],
  "options": [
    "setClasses"
  ],
  "uglify": true
}
```

**Comment by regisphilibert** [comment]
We had to abandon grunt-modernizr all together on our last project because of this :( Would be really nice to see this addressed... cssgrid is soon to be an essential modernizr test.

**Comment by patrickkettner** [comment]
@Hlsgs @regisphilibert had you upgraded your local version of modernizr to one that includes those detects?

**Comment by davemac** [comment]
@patrickkettner I'm getting the same issue. Correct me if I'm wrong but doesn't grunt-modernizr build a custom modernizr package, so the local modernizr version doesn't need to exist for it to do so?

**Comment by josephbergdoll** [comment]
+1

**Comment by rejas** [comment]
Hi @Hlsgs could you try again with the latest version 2.0.1 ?

**Comment by Hlsgs** [comment]
This now works as it should:
```
{
  "crawl": false,
  "customTests": [],
  "dest": "/PATH/TO/modernizr-output.js",
  "tests": [
    "touchevents",
    [
      "cssgrid",
      "cssgridlegacy"
    ]
  ],
  "options": [
    "setClasses"
  ],
  "uglify": true
}
```
Awesome!
