### ISSUE TITLE
Is there any way to merge modernizr Output file into another file.

### ISSUE THREAD

**Issue by jitendra-khatri** [Modernizr/grunt-modernizr#160]
I am having a project setup with grunt and it generates some files, 2 files are there which i want to merge is : 1. modernizr output file and 1. vendor.js (consisting of all third party dependencies)

Is it possible in some way by providing modernizr configurations?

**Comment by rejas** [comment]
Hi @jitendra-khatri sorry but this functionality is not in the scope of grunt-modernizr. Maybe you should check out https://github.com/gruntjs/grunt-contrib-concat
