### ISSUE TITLE
Modernizr 1.0.2 not working anymore

### ISSUE THREAD

**Issue by Heidschnucke** [Modernizr/grunt-modernizr#166]
Hello friends,

since modernizr uses customizr as a dependency and this dependency is no longer available on https://github.com/doctyper/customizr/tarball/develop, modernizr version 1 is not working anymore.

Is there any chance to get this working again?

Best Regards

**Comment by rejas** [comment]
Isnt it possible for you to upgrad to the latest version?

**Comment by mashbodeploy** [comment]
Pretty sure we've just hit this as well on a legacy project, we're on version 1.0.3.

```
error An unexpected error occurred: "https://github.com/Modernizr/customizr/tarball/develop: Request failed \"404 Not Found\"".
```
Different path though.

Ideally we wouldn't have to upgrade as we weren't planning on making any changes to this projects build.

**Comment by mashbodeploy** [comment]
Upgrading to 2.1.1 though hasn't presented any immediate issues in development.

**Comment by mikemellor11** [comment]
Upgrading isn't an option for everybody though, for us this dependancy isn't one we've specificed but one in a nested package that we haven't authored. Is there a reason the url can't be redirected or fixed so it doesn't 404?

**Comment by rejas** [comment]
Which nested package do you mean?

**Comment by mikemellor11** [comment]
Not too sure how useful that information is, but it's this one https://www.npmjs.com/package/@fishawack/config-grunt. The issue is whatever update has happened recently has broken all pre v2 versions? Surely there's a way to keep the legacy code up so this isn't the case?

**Comment by rejas** [comment]
config-grunt has been updated to use the latest version...

I also created a develop branch again on the customizr to make the old builds run again. I will mark those (<= 1.3) deprecated on npm though to show people that they should upgrade to something that doesnt has hardcoded urls in the package.json

**Comment by mikemellor11** [comment]
It has but that isn’t really the point, to update some of our repos to the latest version of config grunt would be a lot more work than simply bumping the modernizr dep. Thanks for sorting this.
