### ISSUE TITLE
Not working with node 6.10.1 and npm 3.10.10

### ISSUE THREAD

**Issue by pucciodan** [Modernizr/grunt-modernizr#167]
Issue with new release, i think, because until monday morning everything worked fine.
Basically grunt task not working anymore with node 6.10.1 and npm 3.10.10. I got an "unexpected token" warning and task runner fails.
The configuration was generated directly with modernizr build tool and is
```json
modernizr: {
            dist: {
                "crawl": false,
                "customTests": [],
                "dest": "<%= Folders.Dist %>/javascript/vendor/modernizr_custom.js",
                "tests": [
                    [
                        "cssgrid",
                        "cssgridlegacy"
                    ],
                    "flexbox"
                ],
                "options": [
                    "setClasses"
                ],
                "uglify": true
            }
        },
```
I tried with grunt-modernizr versions 2.0.1 and 2.1.1

After several attempts it turns out that if I set uglify to false, it works. But obviously the generated file is not uglified.

With latest node version everything works fine.

**Comment by nikjuice** [comment]
Have the same issue now with Node 4.0.0 and npm 3.3.6

```
Running "modernizr:dist" (modernizr) task
Warning: Unexpected token { Use --force to continue.
Aborted due to warnings.
```

**Comment by rejas** [comment]
hi @pucciodan  @nikjuice sorry for the dela yin answering. could you delete your node_modules folder (and a package-lock.json if there is one) and do a npm install ? Maybe the Modernizr 3.9.0 is the culprit and using the 3.9.1 in the dependecnies will help you.

**Comment by nikjuice** [comment]
Hi @rejas !

No problem! I was able to fix it with attached shrink file, where I forced the old version of  customizr and modernizr . It may be not fully correct, but it solved the issue for me in the legacy project. 


[npm-shrinkwrap.zip](https://github.com/Modernizr/grunt-modernizr/files/4287729/npm-shrinkwrap.zip)

**Comment by moonshark** [comment]
> Hi @rejas !
> 
> No problem! I was able to fix it with attached shrink file, where I forced the old version of customizr and modernizr . It may be not fully correct, but it solved the issue for me in the legacy project.
> 
> [npm-shrinkwrap.zip](https://github.com/Modernizr/grunt-modernizr/files/4287729/npm-shrinkwrap.zip)
> 
> P.S. deleting of lock file and npm_modules + clear the npm cache did not help.

I am able to get this working using your npm-shrinkwrap.zip file but I was hoping to know if it was possible to force the Customizr version directly into the package.json? 

For some reason, when I run npm install it is not creating a package-lock.json file.

My package.json file is:

`{
  "name": "testing",
  "version": "0.1.0",
  "devDependencies": {
    "autoprefixer": "^6.1.2",
    "grunt": "^0.4.5",
    "grunt-bower-concat": "^1.0.0",
    "grunt-bower-install-simple": "^1.2.4",
    "grunt-bowercopy": "^1.2.4",
    "grunt-browser-sync": "^2.1.3",
    "grunt-contrib-clean": "^0.7.0",
    "grunt-contrib-concat": "^0.5.1",
    "grunt-contrib-connect": "^1.0.2",
    "grunt-contrib-copy": "^0.8.2",
    "grunt-contrib-jshint": "^0.11.3",
    "grunt-contrib-uglify": "^0.8.0",
    "grunt-contrib-watch": "~0.6.1",
    "grunt-grunticon": "^2.2.2",
    "grunt-jekyll": "^0.4.6",
    "grunt-jsonlint": "^1.0.6",
    "grunt-modernizr": "1.0.2",
    "grunt-newer": "^1.1.0",
    "grunt-postcss": "^0.7.1",
    "grunt-remove-logging": "^0.2.0",
    "grunt-sass": "^1.1.0",
    "grunt-sass-directory-import": "^0.1.4",
    "grunt-spritesmith": "^6.6.3",
    "jit-grunt": "^0.10.0",
    "load-grunt-config": "^0.19.2",
    "load-grunt-tasks": "^3.3.0",
    "lost": "^6.6.2",
    "postcss-reporter": "^1.3.3",
    "postcss-scss": "^0.1.7",
    "stylelint": "^7.5.0"
  }
}
`
