### ISSUE TITLE
Request failed \"404 Not Found\"". https://github.com/Modernizr/customizr/tarball/develop

### ISSUE THREAD

**Issue by vijayakarunakar** [Modernizr/grunt-modernizr#171]
Getting below issue:
node version: 10.23.0
Yarn version : 1.22.10
Executing command : yarn install 
error An unexpected error occurred: "https://github.com/Modernizr/customizr/tarball/develop: Request failed \"404 Not Found\"".

**Comment by rejas** [comment]
@vijayakarunakar  What version of grunt-modernizr are you using? Can you upgrade to the latest?

**Comment by vijayakarunakar** [comment]
@rejas using grunt-modernizr version: 1.0.3, I'm hoping upgrading will cause more issues since there are lot of other dependencies.

**Comment by vijayakarunakar** [comment]
it was working earlier, 2-3 weeks back. https://codeload.github.com/Modernizr/customizr/legacy.tar.gz/develop has been removed recently?

**Comment by rejas** [comment]
@doctyper removed his branch probably that is behind your legacy package. See https://github.com/Modernizr/grunt-modernizr/issues/146

I wont be able to add it here, therefor I strongly advise to update

**Comment by vijayakarunakar** [comment]
sure I will update, Thanks.

**Comment by mikemellor11** [comment]
Updating isn't always feasible, some of these repo's are legecy projects where this package itself is a subpackage of another and updating the parent package would be a major code update. Is there any possiblity of recreating the branch and potentially protecting it so it isn't removed again in future.

**Comment by babureddyc** [comment]
We have changed **grunt-modernizr from 1.0.2 to 2.0.1**. Though it is not latest version we felt it is nearly compatible with other grunt/npm software's. also make sure you test your system if you follow this. I might be lucky to get it worked. it may not solve your problem completely.
