### ISSUE TITLE
className prefix option

### ISSUE THREAD

**Issue by ghost** [Modernizr/grunt-modernizr#47]
I see this issue https://github.com/Modernizr/grunt-modernizr/issues/30, but it seems it doesn't work. How should i use this option? Thank you.

**Comment by MelchnerRoman** [comment]
Just to show you guys how i´ve done it after being stuck for an hour in grunt 
`
    modernizr: {
                dist: {
                  "crawl": false,
                  "customTests": [],
                  "dest": "assets/modernizr.min.js",
                  "classPrefix": "supports-",
                  "tests": [
                    "flexbox",
                    "fontface",
                    "csstransforms",
                    "csstransforms3d",
                  ],
                  "options": [
                    "domPrefixes",
                    "prefixes",
                    "testAllProps",
                    "testProp",
                    "testStyles",
                    "setClasses",
                  ],
                  "uglify": true,
                },
            },
`
