### ISSUE TITLE
SVG, audio, and video false positives

### ISSUE THREAD

**Issue by robwierzbowski** [Modernizr/grunt-modernizr#49]
Not sure if this is resolvable, but I'm getting a number of false positives.

##### CSS

Normalize svg declaration is triggering SVG:

```
svg:not(:root) {
  overflow: hidden;
}
```

A custom Sass function is triggering audio:

```css
&:before {
  content: icon(audio);
}
```

##### JS

Mediaelement.js is triggering audio, video, and svg with the many times it references those strings.

##### Solution?

Would adding a `.` before the feature tests in CSS be workable? I think that would fix a lot of false positives.

Not sure what would work for JS. There might not be a perfect solution aside from manually specifying tests.

**Comment by gunnx** [comment]
+1

**Comment by patrickkettner** [comment]
closing due to age and project changes.

If anyone is interested in this still, please open up a new issue on [customizr](https://github.com/Modernizr/customizr/issues/new)
