### ISSUE TITLE
Add tests: ['all'] to allow users to generate dev file

### ISSUE THREAD

**Issue by robwierzbowski** [Modernizr/grunt-modernizr#53]
With the current devfile approach:

If you're generating your own devfile, for maximum safety you have to manually keep it in sync with the Modernizr build that Grunt-modernizr is creating. 

If you're using a front-end package manager like Bower... well there is an unofficial Modernizr Bower package, but being managed outside of the core project it's not the best thing to rely on.

A user could set up two tasks, one for `:serve` / development, and one for build. With an `all` keyword for tests it would be easy to generate a version-correct full modernizr build for development.

**Comment by patrickkettner** [comment]
given that we migrated over to customizr for detection of features, this is no longer in the scope of this project
