### ISSUE TITLE
Standalone tool

### ISSUE THREAD

**Issue by sindresorhus** [Modernizr/grunt-modernizr#54]
This shouldn't be coupled with grunt, but instead be a standalone tool that a simple grunt task could depend on. That way people not using grunt can take advantage of it and there can be plugins for other build-systems like [gulp](http://gulpjs.com).

We recently did that with https://github.com/yeoman/bower-requirejs where grunt-bower-requirejs is now just a "dumb" grunt task https://github.com/yeoman/grunt-bower-requirejs/blob/master/tasks/bower-requirejs.js depending on it.

**Comment by patrickkettner** [comment]
we moved over to using customizr a while back, closing this one out as complete
