### ISSUE TITLE
define is undefined when including 'videoautoplay' custom test

### ISSUE THREAD

**Issue by IbeVanmeenen** [Modernizr/grunt-modernizr#60]
When I include the custom test videoautoplay (https://github.com/Modernizr/Modernizr/blob/master/feature-detects/video/autoplay.js) the build throws the error 'define is undefined' (see screenshot). 
![screen shot 2014-02-04 at 13 50 00](https://f.cloud.github.com/assets/673778/2076175/e26c621c-8d9c-11e3-82ed-cbfaf6a505a9.png)

Any idea how to fix this?

Thanks!

**Comment by patrickkettner** [comment]
@IbeVanmeenen sorry you never got a reply :[

this is because videoautoplay is a v3 test, and the project is built using v2. It will be updated shortly to support this (though I hope it is not an issue for you for this long)
