### ISSUE TITLE
Attempts to download `filereader.js` instead of `file-api.js`

### ISSUE THREAD

**Issue by craigmdennis** [Modernizr/grunt-modernizr#93]
Modernizr correctly detects the `.filereader` class being used in my stylesheet but tries to download the `filereader.js` insted of `file-api.js` which contains the filereader test.

Error is as follows:

<pre>
Downloading community files
cache file-api.js
404 filereader.js

>> Generating a custom Modernizr build
>> Skipping uglify

>> Wrote file to .tmp/scripts/modernizr.js
>> The following tests could not be downloaded
>>     
>>     404 http://modernizr.com/Modernizr/Modernizr/87c723720a48254ae37ffd56829e32a96f5c5496/feature-detects/filereader.js
>>     
>>     Check the Modulizr API for more info:
>>     https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modulizr.js#L15-157

</pre>

**Comment by edmelly** [comment]
I am seeing the same issue with v0.6.0 :

404 http://modernizr.com/Modernizr/Modernizr/87c723720a48254ae37ffd56829e32a96f5c5496/feature-detects/filereader.js

That is caused by including `Modernizr.filereader` in my JavaScript.
