### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by resting** [Modernizr/grunt-modernizr#96]
I did the following steps.
1. `git clone https://github.com/Modernizr/grunt-modernizr`
2. `cd grunt-modernizr && npm i --save-dev`
3. `npm test`

The test fails with

```
Downloading source files
200 modernizr-latest.js
200 modernizr.load.1.5.4.js

Downloading community files
200 json.js
200 contextmenu.js
200 emoji.js

>> Generating a custom Modernizr build
>> Uglifying
Fatal error: Unexpected character ''
    1) should find all available tests in project
         AssertionError: expected "Fatal error: Unexpected character '\u001f'\u0007" to contain ">> Wrote file to build/modernizr-custom.js"

npm ERR! Test failed.  See above for more details.
npm ERR! not ok code 0
```

Also, the file `lib/cache/modernizr-latest.js` is scrambled with weird characters as if it was a binary.
Anyone has any idea what's wrong?

**Comment by 2silver** [comment]
I did the following steps.

    git clone https://github.com/Modernizr/grunt-modernizr
    cd grunt-modernizr && npm i --save-dev
    npm test

The test fails with

    >> Generating a custom Modernizr build
    >> Uglifying
    Fatal error: Unexpected character ''
        1) should find all available tests in project
             AssertionError: expected "Fatal error: Unexpected character '\u001f'\u0007" to contain ">> Wrote file to build/modernizr-custom.js"
    
    
      custom builds
        community tests
          2) should find all available tests in project
             Error: done() called multiple times
    
    npm ERR! Test failed.  See above for more details.
